# Generated by Django 4.1.2 on 2022-11-18 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_order_id_alter_orderitem_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order", name="quantity", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="order",
            name="paid_amount",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
    ]
