# Generated by Django 4.1.2 on 2022-11-18 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_order_quantity_alter_order_paid_amount"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="quantity",),
    ]
